Public Class POCO
    Public Property ID As Integer '(int, not null)
    Public Property _01bigint As Long '(bigint, null)
    Public Property _02binary() As Byte '(binary(50), null)
    Public Property _03bit As Boolean '(bit, null)
    Public Property _03char As String '(char(10), null)
    Public Property _04date As DateTime '(date, null)
    Public Property _05datetime As DateTime '(datetime, null)
    Public Property _06datetime2 As DateTime '(datetime2(7), null)
    Public Property _07datetimeoffset As DateTimeOffset '(datetimeoffset, null)
    Public Property _09decimal As Decimal '(decimal(18,0), null)
    Public Property _10float As Double '(float, null)
    Public Property _11geography As Microsoft.SqlServer.Types.SqlGeography '(Chinook.sys.geography, null)
    Public Property _12geometry As Microsoft.SqlServer.Types.SqlGeography '(Chinook.sys.geometry, null)
    Public Property _13hierachyid As Microsoft.SqlServer.Types.SqlGeography '(Chinook.sys.hierarchyid, null)
    Public Property _14image() As Byte '(image, null)
    Public Property _15int As Integer '(int, null)
    Public Property _16money As Decimal '(money, null)
    Public Property _17nchar As String '(nchar(10), null)
    Public Property _18ntext As String '(ntext, null)
    Public Property _19numeric As Decimal '(decimal(18,0), null)
    Public Property _20nvarchar As String '(nvarchar(50), null)
    Public Property _21nvarcharMax As String '(nvarchar(max), null)
    Public Property _22real As Single '(real, null)
    Public Property _23smalldatetime As DateTime '(smalldatetime, null)
    Public Property _24sql_variant As Object '(sql_variant, null)
    Public Property _25text As String '(text, null)
    Public Property _26time As DateTime '(time(7), null)
    Public Property _27timestamp() As Byte '(timestamp, null)
    Public Property _28tinyint() As Byte '(tinyint, null)
    Public Property _29uniqueidentifier As Guid '(uniqueidentifier, null)
    Public Property _30varbinary() As Byte '(varbinary(50), null)
    Public Property _31varbinaryMax() As Byte '(varbinary(max), null)
    Public Property _32varchar As String '(varchar(50), null)
    Public Property _33varcharMax As String '(varchar(max), null)
    Public Property _34xml As String '(XML(.), null)
End Class
